#!/usr/bin/env perl
=h

=cut
use strict;
use Net::FTP;
use Fatal qw(open close);
if(!$ENV{"EVE_HOME"}){
		die "You must set EVE_HOME first\n";
}
my $eve_home = $ENV{"EVE_HOME"};
my $string="ftp://ftp.gnome.org/pub/gnome/sources";

my ($server,$user,$pass,$directory);
if($string=~/^ftp:\/\/(?:([^:\@]+):([^\@]+)\@)?([^\/]+)\/(\S+)/){
		($server,$user,$pass,$directory)=($3,$1,$2,$4);
		$directory="./$directory";
		$user = "anonymous" if $user eq "";
		$pass = '-anonymous@' if $pass eq "";
}
my $ftp = Net::FTP->new($server, Timeout => 30)
		or die "Can not connect to $server : $@\n";
$ftp->login($user, $pass)
		or die "Can not login using credentials : $@\n";
$ftp->binary()
		or die "Can not switch to binary mode : $@\n";
$ftp->cwd($directory)
		or die "Can not change directories to $directory : $@\n";
my @files = $ftp->dir();
open O,">$eve_home/conf/genome.packages";
foreach my $file (@files) {
		my @l=split /\s+/,$file;
		print O "$l[-1]\tgenome $l[-1]\tftp://ftp.gnome.org/pub/gnome/sources/$l[-1]/\t1\tlatest:^(?!cache.json)|latest:tar\\.[glxb]z2?\$|wget\ttar|conf|inst\n";
}
close O;
$ftp->close();
sub islower(){
		my $c=shift;
		return $c ge 'a' && $c le 'z';
}			 


