#!/bin/sh
if ! [ -n "$EVE_HOME" ] ; then echo 'EVE_HOME is not set' exit; fi
pm=$EVE_HOME/pm
$pm i xz
$pm i autoconf
$pm i automake 
$pm i libtool 
$pm i gmp
$pm i mpfr
$pm i mpc
$pm i gcc
$pm i gawk
$pm i texinfo
$pm i gettext
$pm i glibc	#require gawk texinfo gettext
$pm i ncurses
$pm i emacs --without-x
$pm i php --enable-fpm --enable-mbstring --with-openssl --with-mcrypt
$pm i gnutls2 --without-p11-kit --with-included-libtasn1 #or not work